### ISSUE TITLE
Publish Loco adapter on http://symfony.sh/

### ISSUE THREAD

**Issue by welcoMattic** [php-translation/loco-adapter#32]
It would be nice to make the Adapters installable by Symfony Flex. For that we need to move `TranslationAdapterLocoBundle` to let Flex understands it's a bundle, and add it automatically in bundles.php.

**Comment by Nyholm** [comment]
Excellent idea. If you make a PR to symfony/recipe-contrib then I'll make sure to merge it.

**Comment by Nyholm** [comment]
Any updates?

**Comment by welcoMattic** [comment]
No, sorry. I'm currently teaching students right now, so I don't have time to work on it. May be this weekend, not sure

**Comment by Nyholm** [comment]
Okey. If you submit the recipe it will be reviewed way quicker than if I submit it.

**Comment by franmomu** [comment]
Hi, I've just submitted https://github.com/symfony/recipes-contrib/pull/518, but apparently this package is registered as library https://symfony.sh/r/github.com/symfony/recipes-contrib/518

https://symfony.com/doc/current/bundles/best_practices.html#installation

**Comment by Nyholm** [comment]
This if fixed!

Thank you
