### ISSUE TITLE
Add phraseapp-adapter repo

### ISSUE THREAD

**Issue by prolic** [php-translation/loco-adapter#4]
Can you please create a adapter-repo for https://phraseapp.com/?
I will write the source code and tests for it the next days.

@Nyholm

**Comment by prolic** [comment]
Initial skeleton repo is here: https://github.com/prolic/phraseapp-adapter

I'll push the implementation as soon as it's ready.

**Comment by Nyholm** [comment]
Of course, I just created the repo and gave you write permissions. 

Thank you.

**Comment by prolic** [comment]
Also TravisCI, Scrutinizer and packagist & co is required.
I just pushed the initial skeleton with composer.json to https://github.com/php-translation/phraseapp-adapter

Thanks.

**Comment by Nyholm** [comment]
I've enabled all those services now.

**Comment by prolic** [comment]
Thanks

Am 21.01.2017 22:11 schrieb "Tobias Nyholm" <notifications@github.com>:

I've enabled all those services now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/php-translation/loco-adapter/issues/4#issuecomment-274264005>,
or mute the thread

**Comment by Nyholm** [comment]
Thank you!
