### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by I-Valchev** [php-translation/loco-adapter#55]
Is there a plan to support 8.0 soon-ish? Thanks.

**Comment by welcoMattic** [comment]
Hi @I-Valchev 

There is no plan to immediately support PHP 8, but it will happen.
Feel free to submit a PR on this adapter and on the Symfony bundle if you need this support quickly :wink: 

Thank you for your comment

**Comment by Nyholm** [comment]
This is fixed in master. Im doing a release now.
