### ISSUE TITLE
domains config not working

### ISSUE THREAD

**Issue by toooni** [php-translation/loco-adapter#6]
In the `Readme.md` is an option which describes to use the `domains` configuration to use tags for domains. This isn't really an option at the moment (afaik) because tags aren't created from the api.
This results in an issue where translations without tags are created on loco and existing translations are added to wrong/all domains locally when running the `translation:sync` command.

**Comment by pimolo** [comment]
I'm currently working on something to allow this. Indeed, it's not properly supported atm.
